Functional requirements.md

Work in progress… Not yet finished!
@DANS-KNAW/easy feedback is already welcome.

EASY-1067 - Functional requirements

---

Functional requirements.md

~~fixes EASY-~~
* update this repository according to the renaming changes in [PR#57 in Easy-Sword2](https://github.com/DANS-KNAW/easy-sword2/pull/57)
easy-sword2                      | [PR#57](https://github.com/DANS-KNAW/easy-sword2/pull/57)

rename 'deposit' to 'sword2'

---

src/main/scala/nl/knaw/dans/easy/license/TemplateResolver.scala

encoding to fix quotes

---

src/main/scala/nl/knaw/dans/easy/license/FileItem.scala
src/main/scala/nl/knaw/dans/easy/license/package.scala

fixes EASY-
* fix the build error in easy-app
* 
* 
easy-                      | [PR#](PRlink)

build fix for easy-app

---

README.md
pom.xml
src/main/scala/nl/knaw/dans/easy/license/app/CommandLineOptions.scala

fixes EASY-1049 Upgrade scallop
* upgrade scallop to version 2.0.2
@DANS-KNAW/easy please review

upgrade scallop to 2.0.2

---

debug-reset-apphome.sh
pom.xml
run-service.sh
src/main/assembly/dist/bin/easy-license-creator-initd.sh
src/main/assembly/dist/bin/easy-license-creator-service-start
src/main/assembly/dist/bin/easy-license-creator.service
src/main/assembly/dist/cfg/application.properties
src/main/scala/ScalatraBootstrap.scala
src/main/scala/nl/knaw/dans/easy/license/FileItem.scala
src/main/scala/nl/knaw/dans/easy/license/LicenseCreator.scala
src/main/scala/nl/knaw/dans/easy/license/Parameters.scala
src/main/scala/nl/knaw/dans/easy/license/app/ApplicationSettings.scala
src/main/scala/nl/knaw/dans/easy/license/app/Command.scala
src/main/scala/nl/knaw/dans/easy/license/app/CommandLineOptions.scala
src/main/scala/nl/knaw/dans/easy/license/app/LicenseCreatorService.scala
src/main/scala/nl/knaw/dans/easy/license/app/ServiceStarter.scala
src/main/scala/nl/knaw/dans/easy/license/internal/DatasetLoader.scala
src/main/scala/nl/knaw/dans/easy/license/internal/Fedora.scala
src/main/scala/nl/knaw/dans/easy/license/internal/Ldap.scala
src/main/scala/nl/knaw/dans/easy/license/internal/Parameters.scala
src/main/scala/nl/knaw/dans/easy/license/internal/PdfGenerator.scala
src/main/scala/nl/knaw/dans/easy/license/internal/PlaceholderMapper.scala
src/main/scala/nl/knaw/dans/easy/license/internal/TemplateResolver.scala
src/main/scala/nl/knaw/dans/easy/license/internal/package.scala
src/test/resources/debug-config/application.properties
src/test/resources/debug-config/logback-service.xml

No JIRA issue.
* Expose the license creator as a RESTful service
Perhaps [here](https://github.com/DANS-KNAW/easy-license-creator/compare/master...janvanmansum:LICENSE_AS_A_SERVICE#diff-47005b92a437c3545210c8e9a888ffc6R36)
* Install it on `deasy` and check it with `sudo service easy-license-creator status`, etc.
* `curl -X POST http://localhost:8060/create?datasetId=easy-dataset:1` on `deasy`.

License as a service

---

.gitignore
debug-reset-apphome.sh
pom.xml
src/main/assembly/dist/bin/easy-license-creator
src/main/assembly/dist/bin/easy-license-creator-initd.sh
src/main/assembly/dist/cfg/logback-service.xml
src/main/assembly/dist/cfg/logback.xml
src/main/scala/nl/knaw/dans/easy/license/internal/DatasetLoader.scala
src/main/scala/nl/knaw/dans/easy/license/internal/package.scala
src/test/resources/debug-config/application.properties
src/test/resources/debug-config/logback-service.xml
src/test/resources/debug-config/logback.xml
src/test/resources/debug-config/pdfgen.sh
src/test/scala/nl/knaw/dans/easy/license/internal/DatasetLoaderSpec.scala
src/test/scala/nl/knaw/dans/easy/license/internal/PlaceholderMapperSpec.scala
src/test/scala/nl/knaw/dans/easy/license/internal/VelocityTemplateResolverSpec.scala

fixes EASY-1193
* add debug deploy facilities
* update the emd version to 2.17-beta-4 (@lindareijnhoudt can you check this is the correct version?)
* add the original exception to the newly created exception
* improve the test suite with new inside from the last months
easy-dtap | [PR#77](https://github.com/DANS-KNAW/easy-dtap/pull/77) |

Easy-1193 - foutieve foutmelding bij problemen met EMD

---

src/main/assembly/dist/res/template/Header.html

~~fixes EASY-~~ (as requested by @lindareijnhoudt)
* change the doi base url to the correct one
easy-app                      | [PR#84](https://github.com/DANS-KNAW/easy-dtap/pull/84)
easy-dtap                      | [PR#71](https://github.com/DANS-KNAW/easy-app/pull/71)

change doi base url

---

pom.xml

@DANS-KNAW/easy
Merge all at once
=============
fixes EASY-1260 editable DDM relation
master PR: https://github.com/DANS-KNAW/easy-app/pull/78

EASY-1260 editable DDM relation

---

pom.xml

roll back to jetty 8.x, waiting for fix for jetty 9.x by @janvanmansum

back to jetty 8.x

---

pom.xml

emd version bump to 3.5
@DANS-KNAW/easy

emd version bump to 3.5

---

src/main/scala/nl.knaw.dans.easy.license/Command.scala
src/main/scala/nl.knaw.dans.easy.license/LicenseCreatorServlet.scala

@DANS-KNAW/easy for review
I forgot to close the connection of FSRDB

forgot to close connection

---

pom.xml
src/main/scala/nl.knaw.dans.easy.license/internal/PlaceholderMapper.scala

part of EASY-1524
@DANS-KNAW/easy for review

EASY-1524: Implement MultiSurface in DDM and EMD

---

src/main/assembly/dist/res/template/FileTable.html
src/main/scala/nl.knaw.dans.easy.license/internal/PlaceholderMapper.scala

fixes EASY-1566
* fix the `NullPointerException` by removing the `Polygon` data all together
@DANS-KNAW/easy for review

EASY-1566: fix NullPointerException and remove polygon data

---

src/main/assembly/dist/install/easy-license-creator.service

fixes EASY-1823
* add status=143 as success code
Where should the reviewer @DANS-KNAW/easy start?

 EASY-1823: add status=143 as success code

---

pom.xml
src/main/scala/nl/knaw/dans/easy/agreement/AgreementCreatorServlet.scala

fixes EASY-1981
* add servlet logging with plain logging, without masking
* 
*

EASY-1981: Add servlet logging

---

src/main/scala/nl/knaw/dans/easy/agreement/AgreementCreatorApp.scala
src/main/scala/nl/knaw/dans/easy/agreement/AgreementCreatorServlet.scala

fixes EASY-2002 add version to baseurl response
* add version to baseurl response
easy-                      | [PR#](PRlink)

EASY-2002: add version to baseurl response

---

pom.xml
src/main/scala/nl/knaw/dans/easy/agreement/AgreementCreatorServlet.scala
src/main/scala/nl/knaw/dans/easy/agreement/Command.scala
src/main/scala/nl/knaw/dans/easy/agreement/internal/Fedora.scala
src/test/scala/nl/knaw/dans/easy/agreement/AgreementCreatorServletSpec.scala
src/test/scala/nl/knaw/dans/easy/agreement/UnitSpec.scala

fixesEASY-1982 check if datasetId exists before querying EMD
*  will first check if the datasetId exist before querying the EMD
*  if it does not exist an 404 is returned 
* if the parameter ?datasetId=<id> is not provided is returns a 400
easy-                      | [PR#](PRlink)

EASY-1982 check if datasetId exists before querying EMD

---

README.md
docs/api/api.yml
docs/index.md

fixes EASY-2400
* update documentation to be in line with other projects
* 
* 
easy-                      | [PR#](PRlink)

EASY-2400 update documentation

---

src/main/assembly/dist/cfg/application.properties
src/main/scala/nl/knaw/dans/easy/agreement/AgreementGenerator.scala
src/main/scala/nl/knaw/dans/easy/agreement/Configuration.scala
src/test/resources/debug-config/application.properties
src/test/scala/nl/knaw/dans/easy/agreement/AgreementGeneratorSpec.scala

fixes EASY-2475
* add configurable timeouts for call to `easy-deposit-agreement-generator`
@DANS-KNAW/easy for review

EASY-2475: configurable timeout for call to easy-deposit-agreement-generator
